// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2025-03-02 18:59:14
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`include "n_core.svh"

module n_core (
	input logic unsigned [0:0] clk_i
	, input logic unsigned [0:0] rst_i
);




always_comb
	begin
	// Buffering globals
	// Processing dlychains
	// fifo_in buffering
	// subproc fifo_in buffering
	// Payload logic
	end


endmodule
