// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2025-02-27 15:03:03
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`include "Neuromorphic_design.svh"

module Neuromorphic_design (
	input logic unsigned [0:0] clk_i
	, input logic unsigned [0:0] rst_i
	, input logic unsigned [0:0] input_queue_genfifo_req_i
	, input logic unsigned [7:0] input_queue_genfifo_rdata_bi [31:0]
	, output logic unsigned [0:0] input_queue_genfifo_ack_o
	, input logic unsigned [0:0] output_queue_genfifo_req_i
	, input logic unsigned [7:0] output_queue_genfifo_rdata_bi [31:0]
	, output logic unsigned [0:0] output_queue_genfifo_ack_o
);


logic unsigned [31:0] tick;
logic unsigned [31:0] tick_period;
logic unsigned [31:0] clk_counter;
logic unsigned [31:0] next_clk_count;
logic unsigned [0:0] gen4_cyclix_genvar;
logic unsigned [0:0] gen5_cyclix_genvar;
logic unsigned [32:0] gen6_cyclix_genvar;
logic unsigned [0:0] gen7_cyclix_genvar;
logic unsigned [0:0] input_queue_genfifo_buf_ack;
logic unsigned [0:0] input_queue_genfifo_buf_req;
logic unsigned [7:0] input_queue_genfifo_buf_rdata [31:0];
logic unsigned [0:0] output_queue_genfifo_buf_ack;
logic unsigned [0:0] output_queue_genfifo_buf_req;
logic unsigned [7:0] output_queue_genfifo_buf_rdata [31:0];
logic unsigned [0:0] gen0_rtl_var;
logic unsigned [0:0] gen1_rtl_var;

logic unsigned [31:0] gensticky_tick;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_tick <= 32'd0;
		end
	else
		begin
		gensticky_tick <= tick;
		end

logic unsigned [31:0] gensticky_tick_period;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_tick_period <= 32'd50;
		end
	else
		begin
		gensticky_tick_period <= tick_period;
		end

logic unsigned [31:0] gensticky_clk_counter;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_clk_counter <= 32'd0;
		end
	else
		begin
		gensticky_clk_counter <= clk_counter;
		end

logic unsigned [31:0] gensticky_next_clk_count;
always_ff @(posedge clk_i)
	if (rst_i)
		begin
		gensticky_next_clk_count <= 32'd0;
		end
	else
		begin
		gensticky_next_clk_count <= next_clk_count;
		end


always_comb
	begin
	input_queue_genfifo_ack_o = input_queue_genfifo_buf_ack;
	end

always_comb
	begin
	output_queue_genfifo_ack_o = output_queue_genfifo_buf_ack;
	end

always_comb
	begin
	tick = 32'd0;
	gen6_cyclix_genvar = 32'd0;
	next_clk_count = 32'd0;
	clk_counter = 32'd0;
	tick_period = gensticky_tick_period;
	tick = gensticky_tick;
	next_clk_count = gensticky_next_clk_count;
	clk_counter = gensticky_clk_counter;
	// Buffering globals
	// Processing dlychains
	// fifo_in buffering
	input_queue_genfifo_buf_req = input_queue_genfifo_req_i;
	input_queue_genfifo_buf_rdata[0] = input_queue_genfifo_rdata_bi[0];
	input_queue_genfifo_buf_rdata[1] = input_queue_genfifo_rdata_bi[1];
	input_queue_genfifo_buf_rdata[2] = input_queue_genfifo_rdata_bi[2];
	input_queue_genfifo_buf_rdata[3] = input_queue_genfifo_rdata_bi[3];
	input_queue_genfifo_buf_rdata[4] = input_queue_genfifo_rdata_bi[4];
	input_queue_genfifo_buf_rdata[5] = input_queue_genfifo_rdata_bi[5];
	input_queue_genfifo_buf_rdata[6] = input_queue_genfifo_rdata_bi[6];
	input_queue_genfifo_buf_rdata[7] = input_queue_genfifo_rdata_bi[7];
	input_queue_genfifo_buf_rdata[8] = input_queue_genfifo_rdata_bi[8];
	input_queue_genfifo_buf_rdata[9] = input_queue_genfifo_rdata_bi[9];
	input_queue_genfifo_buf_rdata[10] = input_queue_genfifo_rdata_bi[10];
	input_queue_genfifo_buf_rdata[11] = input_queue_genfifo_rdata_bi[11];
	input_queue_genfifo_buf_rdata[12] = input_queue_genfifo_rdata_bi[12];
	input_queue_genfifo_buf_rdata[13] = input_queue_genfifo_rdata_bi[13];
	input_queue_genfifo_buf_rdata[14] = input_queue_genfifo_rdata_bi[14];
	input_queue_genfifo_buf_rdata[15] = input_queue_genfifo_rdata_bi[15];
	input_queue_genfifo_buf_rdata[16] = input_queue_genfifo_rdata_bi[16];
	input_queue_genfifo_buf_rdata[17] = input_queue_genfifo_rdata_bi[17];
	input_queue_genfifo_buf_rdata[18] = input_queue_genfifo_rdata_bi[18];
	input_queue_genfifo_buf_rdata[19] = input_queue_genfifo_rdata_bi[19];
	input_queue_genfifo_buf_rdata[20] = input_queue_genfifo_rdata_bi[20];
	input_queue_genfifo_buf_rdata[21] = input_queue_genfifo_rdata_bi[21];
	input_queue_genfifo_buf_rdata[22] = input_queue_genfifo_rdata_bi[22];
	input_queue_genfifo_buf_rdata[23] = input_queue_genfifo_rdata_bi[23];
	input_queue_genfifo_buf_rdata[24] = input_queue_genfifo_rdata_bi[24];
	input_queue_genfifo_buf_rdata[25] = input_queue_genfifo_rdata_bi[25];
	input_queue_genfifo_buf_rdata[26] = input_queue_genfifo_rdata_bi[26];
	input_queue_genfifo_buf_rdata[27] = input_queue_genfifo_rdata_bi[27];
	input_queue_genfifo_buf_rdata[28] = input_queue_genfifo_rdata_bi[28];
	input_queue_genfifo_buf_rdata[29] = input_queue_genfifo_rdata_bi[29];
	input_queue_genfifo_buf_rdata[30] = input_queue_genfifo_rdata_bi[30];
	input_queue_genfifo_buf_rdata[31] = input_queue_genfifo_rdata_bi[31];
	output_queue_genfifo_buf_req = output_queue_genfifo_req_i;
	output_queue_genfifo_buf_rdata[0] = output_queue_genfifo_rdata_bi[0];
	output_queue_genfifo_buf_rdata[1] = output_queue_genfifo_rdata_bi[1];
	output_queue_genfifo_buf_rdata[2] = output_queue_genfifo_rdata_bi[2];
	output_queue_genfifo_buf_rdata[3] = output_queue_genfifo_rdata_bi[3];
	output_queue_genfifo_buf_rdata[4] = output_queue_genfifo_rdata_bi[4];
	output_queue_genfifo_buf_rdata[5] = output_queue_genfifo_rdata_bi[5];
	output_queue_genfifo_buf_rdata[6] = output_queue_genfifo_rdata_bi[6];
	output_queue_genfifo_buf_rdata[7] = output_queue_genfifo_rdata_bi[7];
	output_queue_genfifo_buf_rdata[8] = output_queue_genfifo_rdata_bi[8];
	output_queue_genfifo_buf_rdata[9] = output_queue_genfifo_rdata_bi[9];
	output_queue_genfifo_buf_rdata[10] = output_queue_genfifo_rdata_bi[10];
	output_queue_genfifo_buf_rdata[11] = output_queue_genfifo_rdata_bi[11];
	output_queue_genfifo_buf_rdata[12] = output_queue_genfifo_rdata_bi[12];
	output_queue_genfifo_buf_rdata[13] = output_queue_genfifo_rdata_bi[13];
	output_queue_genfifo_buf_rdata[14] = output_queue_genfifo_rdata_bi[14];
	output_queue_genfifo_buf_rdata[15] = output_queue_genfifo_rdata_bi[15];
	output_queue_genfifo_buf_rdata[16] = output_queue_genfifo_rdata_bi[16];
	output_queue_genfifo_buf_rdata[17] = output_queue_genfifo_rdata_bi[17];
	output_queue_genfifo_buf_rdata[18] = output_queue_genfifo_rdata_bi[18];
	output_queue_genfifo_buf_rdata[19] = output_queue_genfifo_rdata_bi[19];
	output_queue_genfifo_buf_rdata[20] = output_queue_genfifo_rdata_bi[20];
	output_queue_genfifo_buf_rdata[21] = output_queue_genfifo_rdata_bi[21];
	output_queue_genfifo_buf_rdata[22] = output_queue_genfifo_rdata_bi[22];
	output_queue_genfifo_buf_rdata[23] = output_queue_genfifo_rdata_bi[23];
	output_queue_genfifo_buf_rdata[24] = output_queue_genfifo_rdata_bi[24];
	output_queue_genfifo_buf_rdata[25] = output_queue_genfifo_rdata_bi[25];
	output_queue_genfifo_buf_rdata[26] = output_queue_genfifo_rdata_bi[26];
	output_queue_genfifo_buf_rdata[27] = output_queue_genfifo_rdata_bi[27];
	output_queue_genfifo_buf_rdata[28] = output_queue_genfifo_rdata_bi[28];
	output_queue_genfifo_buf_rdata[29] = output_queue_genfifo_rdata_bi[29];
	output_queue_genfifo_buf_rdata[30] = output_queue_genfifo_rdata_bi[30];
	output_queue_genfifo_buf_rdata[31] = output_queue_genfifo_rdata_bi[31];
	// subproc fifo_in buffering
	// Payload logic
	tick_period = 32'd500;
	gen4_cyclix_genvar = (tick_period != clk_counter);
	gen5_cyclix_genvar = gen4_cyclix_genvar;
	gen0_rtl_var = gen5_cyclix_genvar;
	if (gen0_rtl_var)
		begin
		tick = 32'd0;
		gen6_cyclix_genvar = (clk_counter + 32'd1);
		next_clk_count = gen6_cyclix_genvar;
		clk_counter = next_clk_count;
		end
	gen7_cyclix_genvar = 1'd0;
	gen7_cyclix_genvar = (gen7_cyclix_genvar || gen5_cyclix_genvar);
	gen7_cyclix_genvar = !gen7_cyclix_genvar;
	gen1_rtl_var = gen7_cyclix_genvar;
	if (gen1_rtl_var)
		begin
		tick = 32'd1;
		clk_counter = 32'd0;
		end
	end


endmodule
