// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2025-10-26 03:38:29
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`ifndef __neuromorphic_core_h_
`define __neuromorphic_core_h_

`endif // __neuromorphic_core_h_
